### ISSUE TITLE
MM uses unexpected check type for output field

### ISSUE THREAD

**Issue by neil-yechenwei** [VSChina/magic-modules#25]
Basic.yml:
properties:
virtual_wan:
id:"${azurerm_virtual_wan.<%=resource_id_hint-%>.id}"

.go file:
resource.TestCheckResourceAttr(dataSourceName, "virtual_wan.0.id", "${azurerm_virtual_wan.<%= resource_id_hint -%>.id}"),

**Comment by houkms** [comment]
This issue was solved in PR #40.

**Comment by houkms** [comment]
We provide the features of
- Excluding the resource reference property checking automatically.
- Supporting `property_check_includes` field to specify the properties users want to include from all the properties listed in property filed.
- Supporting `property_check_excludes` field to specify the properties users want to exclude.
- When both are specified, we use `property_check_includes` rather than `property_check_excludes`.

The customization rules in the _basic.yaml_ or _complete.yaml_ are
- The two filed are designed to be array of strings.
- Using the terraform state representation to specify the property.
- Using `prop*` to represent all the sub-properties inside the `prop`.

Here is an example.  And this results in checking only all the representations with prefix `custom_rules.1` in test file.
 ```yaml
--- !ruby/object:Provider::Azure::Example
resource: azurerm_web_application_firewall_policy
prerequisites:
  - !ruby/object:Provider::Azure::ExampleReference
    product: resourcegroup
    example: basic
properties:
  name: "<%= get_resource_name('ApplicationGatewayWebApplicationFirewallPolicies', 'wafpolicy') -%>"
  resource_group_name: ${azurerm_resource_group.<%= resource_id_hint -%>.name}
  location: ${azurerm_resource_group.<%= resource_id_hint -%>.location}
  custom_rules:
    - name: Rule1
      priority: 1
      rule_type: MatchRule
      match_conditions:
        - match_variables:
            - variable_name: RemoteAddr
          operator: IPMatch
          negation_conditon: false
          match_values: [192.168.1.0/24, 10.0.0.0/24]
      action: Block
    - name: Rule2
      priority: 2
      rule_type: MatchRule
      match_conditions:
        - match_variables:
            - variable_name: RemoteAddr
          operator: IPMatch
          negation_conditon: false
          match_values: [192.168.1.0/24]
        - match_variables:
            - variable_name: RequestHeaders
              selector: UserAgent
          operator: Contains
          negation_conditon: false
          match_values: [Windows]
      action: Block
property_check_excludes:
  - custom_rules.#
  - custom_rules.0.*
```
