### ISSUE TITLE
MM should flatten the property when the property only includes id

### ISSUE THREAD

**Issue by neil-yechenwei** [VSChina/magic-modules#37]
Terraform suggests us to flatten the property when the property only includes id. See the comment in the link https://github.com/neil-yechenwei/terraform-provider-azurerm/pull/5

**Comment by houkms** [comment]
I think Magic-Modules supports it well, and let's take the following block as an example.

```yaml
  - !ruby/object:Api::Type::NestedObject
        name: 'vpnGateway'
        description: 'The VpnGateway associated with this VirtualHub.'
        required: false
        azure_sdk_references: ['/vpnGateway', '/properties/vpnGateway']
        properties:
          - !ruby/object:Api::Type::String
            name: 'id'
            description: 'Resource ID.'
            required: false
            azure_sdk_references: ['/vpnGateway/id', '/properties/vpnGateway/id']
```

When you want to flatten the property `id` in `vpnGateway`, just move it to an upper layer and delete its father property if necessary.

```yaml
   - !ruby/object:Api::Type::String
        name: 'vpnGatewayID'
        description: 'Resource ID.'
        required: false
        azure_sdk_references: ['/vpnGateway/id', '/properties/vpnGateway/id']
```

**Remember:** DO NOT modify the paths in `azure_sdk_references` and the declarations in `azure_sdk_definitions`.
