### ISSUE TITLE
MM does not interpret id from another resource in test step assertions

### ISSUE THREAD

**Issue by ArcturusZhang** [VSChina/magic-modules#43]
For instance, this piece of yaml code:
``` yaml
--- !ruby/object:Provider::Azure::Example
resource: azurerm_nat_gateway
prerequisites:
  - !ruby/object:Provider::Azure::ExampleReference
    product: resourcegroup
    example: basic
  - !ruby/object:Provider::Azure::ExampleReference
    product: networkpublicipaddress
    example: basic
properties:
  name: "<%= get_resource_name('natGateway', 'natGateway') -%>"
  location: ${azurerm_resource_group.<%= resource_id_hint -%>.location}
  resource_group_name: ${azurerm_resource_group.<%= resource_id_hint -%>.name}
  public_ip_address_ids: 
    - ${azurerm_public_ip.<%= resource_id_hint -%>.id}
  sku: Standard
  idle_timeout_in_minutes: 10
```
Magic modules generate un-interpreted code in test code as in check steps:
```
resource.TestCheckResourceAttr(resourceName, "public_ip_address_ids.0", "${azurerm_public_ip.<%= resource_id_hint -%>.id}")
```
