### ISSUE TITLE
How to customize the validation functions in schema?

### ISSUE THREAD

**Issue by houkms** [VSChina/magic-modules#44]

**Comment by houkms** [comment]
A good example is [here](https://github.com/Azure/magic-module-specs/blob/master/specs/batchaccount/terraform.yaml) in BatchAccount. 

Firstly, specify the validation function name in `properties`.
Secondly,  include the function's erb file path in `custom_code`.

```yaml
properties:
  name: !ruby/object:Overrides::Terraform::PropertyOverride
    validation: !ruby/object:Provider::Terraform::Validation
      function: validateAzureRMBatchAccountName
custom_code: !ruby/object:Provider::Azure::Terraform::CustomCode
  extra_functions: ./terraform_extra_functions.erb
```
```go
// file name: terraform_extra_functions.erb
func validateAzureRMBatchAccountName(v interface{}, k string) (warnings []string, errors []error) {
    value := v.(string)
    if !regexp.MustCompile(`^[a-z0-9]+$`).MatchString(value) {
        errors = append(errors, fmt.Errorf("letters and numbers only are allowed in %q: %q", k, value))
    }

    if 3 > len(value) {
        errors = append(errors, fmt.Errorf("%q cannot be less than 3 characters: %q", k, value))
    }

    if len(value) > 24 {
        errors = append(errors, fmt.Errorf("%q cannot be longer than 24: %q %d", k, value, len(value)))
    }

    return warnings, errors
}
```
