### ISSUE TITLE
How to override a multi-layer property?

### ISSUE THREAD

**Issue by houkms** [VSChina/magic-modules#45]

**Comment by houkms** [comment]
Use `.` to join the multi-layers. For example, use `p2svpnGateways.id` to specify the property in `properties` field in terraform.yaml file if you want to override the `id` property.

```yaml
- !ruby/object:Api::Type::Array
        name: 'p2svpnGateways'
        description: ''
        output: true
        azure_sdk_references: ['/p2SVpnGateways', '/properties/p2SVpnGateways']
        item_type: !ruby/object:Api::Type::NestedObject
          properties:
            - !ruby/object:Api::Type::String
              name: 'id'
              description: 'Resource ID.'
              required: false
              azure_sdk_references: ['/p2SVpnGateways/id', '/properties/p2SVpnGateways/id']
```
```yaml
overrides: !ruby/object:Overrides::ResourceOverrides
  P2sVpnServerConfiguration: !ruby/object:Provider::Azure::Terraform::ResourceOverride
    properties:
      p2svpnGateways.id: !ruby/object:Provider::Azure::Terraform::PropertyOverride
        exclude: true
```
