### ISSUE TITLE
MM shouldn't generate redundant name for expand and flatten function

### ISSUE THREAD

**Issue by neil-yechenwei** [VSChina/magic-modules#60]
Current Name : expandArmPrivateLinkServicePrivateLinkServicePropertiesAutoApproval
Expect Name : expandArmPrivateLinkServicePropertiesAutoApproval
Current Name : flattenArmPrivateLinkServicePrivateLinkServicePropertiesAutoApproval
Expect Name : flattenArmPrivateLinkServicePropertiesAutoApproval

**Comment by houkms** [comment]
Coding style issue, we need to shorten the function name.

**Comment by magodo** [comment]
The rule used here is defined [here](https://github.com/VSChina/magic-modules/blob/d8afc4be135da4bad108296d3c128e59527cdc51/templates/azure/terraform/flatten_property_method.erb#L25), illustrated below:

```ruby
<%= sdk_marshal.resource -%><%= descriptor.func_name -%>
```

Where:

- `sdk_marshal.resource` equals to:  "Arm" + `Api::Resource.name` (accroding to [this](https://github.com/VSChina/magic-modules/blob/d8afc4be135da4bad108296d3c128e59527cdc51/templates/azure/terraform/resource.erb#L165) and [this](https://github.com/VSChina/magic-modules/blob/d8afc4be135da4bad108296d3c128e59527cdc51/templates/azure/terraform/resource.erb#L22))
- `descriptor.func_name` equals to: `Api::Azure::SDKTypeDefinition.go_type_name`(according to [this](https://github.com/VSChina/magic-modules/blob/d8afc4be135da4bad108296d3c128e59527cdc51/provider/azure/terraform/sdk/expand_flatten_descriptor.rb#L28))

From my understanding, this naming convention make sense. Because currently the folder structure of azure provider code is using flatten pattern, i.e., all resource source files are within same package. Hence:

- To avoid name conflict between different resource, we have to specify `Api::Resource.name` as part of flatten/expand func name
- To avoid name conflict for same resource, but for different data type, we hanve to specify the target go type's name, i.e. `Api::Azure::SDKTypeDefinition.go_type_name` as part of flatten/expand func name

For this specific case, the private link service api.yaml is illustrated below:

```yaml
...
objects:
  - !ruby/object:Api::Resource
    name: PrivateLinkService
    ...
    azure_sdk_definition: !ruby/object:Api::Azure::SDKDefinition
      create: !ruby/object:Api::Azure::SDKOperationDefinition
          ...
          '/properties/autoApproval': !ruby/object:Api::Azure::SDKTypeDefinition::ComplexObject
            ...
            go_type_name: PrivateLinkServicePropertiesAutoApproval
```

IMHO, I think we can introduce a toggle in TF override logic, which is on by default, which will will concat function name in a compact way. In case of a resource has several similar type, one of which has prefix as resource name so as to avoid conflict, then we should turn this toggle off.

@houkms how do you think?
